[build]
command = "npm run build:demo"
publish = "packages/demo-site/public"

[dev]
command = "npm run dev -w packages/demo-site"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
