[build]
command = "npm run build -w packages/demo-site"
publish = "packages/demo-site/public"

[dev]
command = "npm run dev -w packages/demo-site"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"
