[build]
command = "npm run build -w=packages/demo-site"
# command = "npm run build"
publish = "/packages/demo-site/public"

[dev]
command = "npm run dev -w packages/demo-site"


[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"
