[build]
# command = "npm run build && echo '{\"config\":{\"nodeModuleFormat\":\"esm\"},\"version\":1}' > .netlify/functions-internal/server.json"
command = "npm run build"
publish = "public"

[dev]
command = "npm run dev -w packages/demo-site"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"
