[build]
command = "npm run build:edge-demo"
publish = "packages/edge-demo-site/public"


[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
