packages:
  - packages/*
  - demos/*
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  netlify-cli: true
  sharp: false
  unix-dgram: true
  unrs-resolver: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 720 # npm breaches are almost always resolved within 12 hours
