[build]
command = "pnpm --filter demo-site... build"
# command = "npm run build"
publish = "/demos/demo-site/public"

[dev]
command = "pnpm --filter edge-demo-site dev"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"
