name: Run e2e (Remix Demo)
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
jobs:
  e2e:
    name: End-to-end integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Github token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}

      - name: Checkout @netlify/wait-for-deploy-action
        uses: actions/checkout@v4
        with:
          repository: netlify/wait-for-deploy-action
          token: ${{ steps.get-token.outputs.token }}
          path: ./.github/actions/wait-for-netlify-deploy

      - name: Wait for Netlify Deploy
        id: deploy
        uses: ./.github/actions/wait-for-netlify-deploy
        with:
          site-name: remix-serverless
          timeout: 300

      - name: Deploy successful
        if: ${{ steps.deploy.outputs.origin-url }}
        run: echo ${{ steps.deploy.outputs.origin-url }}

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: corepack enable
      - run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ steps.deploy.outputs.origin-url }}
        run: pnpm run test:e2e
        env:
          BASE_URL: ${{ steps.deploy.outputs.origin-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
